<?php
require_once('text_in.class');
require_once('text_out.class');
require_once('job.class');
require_once('person.class');
require_once('feedback.class');
require_once('jobs_relay.class');
require_once('fixit_terms.class');
require_once('fixit_test.class');
require_once('jobadmin.inc');
require_once('hellofixit_sms.rules.inc');
require_once('hellofixit_settings.inc');
require_once('hellofixit_settings_forms.inc');


	function hellofixit_dev(){
		hellofixit_text_in('2543941393','I need my fence mended','fence pic url');
	}

	/*
	 * Implementation of hook_form_alter()
	 */
	function hellofixit_sms_form_alter(&$form, &$form_state, $form_id){
		//just for development
		//dpm($form);
	}

	function hellofixit_text_in($cell,$sms,$mms){
		$newText = array();
		$newText['cell'] = $cell;
		$newText['sms'] = $sms;
		$newText['mms'] = $mms;
		
		//get settings
		$fSettings = hellofixit_settings();
		
		//get taxonomy terms
		$terms1 = new fixit_terms();
		$fTerms = $terms1->main();
				
		//get array of settings to know how to deal with jobs
		$textInSettings = text_in_settings();

		$t1 = new text_in();
		$t1->main($newText,$fTerms,$fSettings,$textInSettings);
	}

	function hellofixit_cron($a,$testMode){
		//If testMode is 1, we are running tests from the settings page in Drupal
		if(!isset($testMode) or $testMode != 1) $testMode = 0;

		//get settings
		$fSettings = hellofixit_settings();

		//check if argument is valid
		if($a !== $fSettings['cron_pw']['value']){
			watchdog('hellofixit','invalid cron password: ' . $a, WATCHDOG_NOTICE);
		}

		//get taxonomy terms
		$terms1 = new fixit_terms();
		$fTerms = $terms1->main();
		
		//get array of settings to know how to deal with jobs
		$jobsRelaySettings = jobs_relay_settings();

		//jobs relay
		$relay1 = new jobs_relay();
		$relay1->main($fTerms,$fSettings,$jobsRelaySettings,$testMode);
	}
	
	function hellofixit_tests(){
		//run tests
		$test1 = new fixit_test();
		$test_results = $test1->main();
		if($test_results['all'] !== 1) return;
	}

	/**
	 * Implements hook_menu()
	 */	 
	function hellofixit_sms_menu(){
		$items['admin/hellofixit/dev'] = array(
			'title' => 'Hellofixit dev',
			'page callback' => 'hellofixit_dev',
			'access arguments' => array('administer users'),
			'type' => MENU_NORMAL_ITEM,
 		);

		$items['admin/hellofixit/settings'] = array(
			'title' => 'Hellofixit settings',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('hellofixit_settings_form'),
			'access arguments' => array('administer users'),
			'type' => MENU_NORMAL_ITEM,
 		);
		
		$items['admin/hellofixit/settings/general'] = array(
			'title' => 'settings',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('hellofixit_settings_form'),
			'access arguments' => array('administer users'),
			'weight' => 1,
			'type' => MENU_DEFAULT_LOCAL_TASK,
 		);
		
		$items['admin/hellofixit/settings/text_in_details'] = array(
			'title' => 'Text-in details',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('hellofixit_text_in_details_form'),
			'access arguments' => array('administer users'),
			'weight' => 2,
			'type' => MENU_LOCAL_TASK,
 		);
		
		$items['admin/hellofixit/settings/job_details'] = array(
			'title' => 'Job Details',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('hellofixit_job_details_form'),
			'access arguments' => array('administer users'),
			'weight' => 3,
			'type' => MENU_LOCAL_TASK,
 		);
		
		$items['admin/hellofixit/cron/%'] = array(
			'title' => 'Hellofixit cron',
			'page callback' => 'hellofixit_cron',
			'page arguments' => array(3),
			'access callback' => array(TRUE),
			'type' => MENU_CALLBACK
		);		
		
		$items['jobadmin/%/%'] = array(
			'title' => 'jobadmin',
			'page callback' => 'job_admin',
			'page arguments' => array(1,2),
			'access callback' => array(TRUE),
			'type' => MENU_CALLBACK
		);
	
	return $items;
	}